"""Transport-neutral Neo Agent SDK and local protocol server."""

from harness.agent_kernel import ReplayProjection

from .bridges import HookAwarePolicyEngine, HookAwareToolRegistry
from .client import (
    Agent,
    Conversation,
    LocalAgent,
    LocalClient,
    RemoteAgent,
    RemoteClient,
)
from .errors import (
    AgentError,
    AgentSDKError,
    AuthenticationError,
    ClosedError,
    ConflictError,
    EventReplayError,
    HTTPError,
    InvalidRequestError,
    MissingVersionError,
    NotFoundError,
    ProtocolError,
    RemoteError,
    RunNotFoundError,
    SDKError,
    SerializationError,
    ToolCatalogError,
    ToolNotFoundError,
    ToolResolutionError,
    TransportError,
    UnsupportedVersionError,
    VersionError,
    VersionMismatchError,
    WorkspaceActiveError,
    WorkspaceError,
    WorkspaceNotFoundError,
)
from .events import Events, EventStream
from .local import LocalTransport
from .models import (
    PROTOCOL_VERSION,
    SCHEMA_VERSION,
    SUPPORTED_PROTOCOL_VERSIONS,
    SUPPORTED_SCHEMA_VERSIONS,
    Capabilities,
    CompletionStatus,
    Event,
    EventEnvelope,
    ProtocolCapabilities,
    QueryRequest,
    Result,
    RunEvent,
    RunRequest,
    RunResult,
    RunSpec,
    Tool,
    ToolCall,
    VersionNegotiation,
)
from .remote import RemoteTransport
from .server import AgentServer, Server
from .transport import AgentTransport, RunHandle, Transport
from .workspace import (
    LocalWorkspaceManager,
    RemoteWorkspaceManager,
    Workspace,
    WorkspaceManager,
)

__all__ = [
    "PROTOCOL_VERSION",
    "SCHEMA_VERSION",
    "SUPPORTED_PROTOCOL_VERSIONS",
    "SUPPORTED_SCHEMA_VERSIONS",
    "Agent",
    "AgentError",
    "AgentSDKError",
    "AgentServer",
    "AgentTransport",
    "AuthenticationError",
    "Capabilities",
    "ClosedError",
    "CompletionStatus",
    "ConflictError",
    "Conversation",
    "Event",
    "EventEnvelope",
    "EventReplayError",
    "EventStream",
    "Events",
    "HTTPError",
    "HookAwarePolicyEngine",
    "HookAwareToolRegistry",
    "InvalidRequestError",
    "LocalAgent",
    "LocalClient",
    "LocalTransport",
    "LocalWorkspaceManager",
    "MissingVersionError",
    "NotFoundError",
    "ProtocolCapabilities",
    "ProtocolError",
    "QueryRequest",
    "RemoteAgent",
    "RemoteClient",
    "RemoteError",
    "RemoteTransport",
    "RemoteWorkspaceManager",
    "ReplayProjection",
    "Result",
    "RunEvent",
    "RunHandle",
    "RunNotFoundError",
    "RunRequest",
    "RunResult",
    "RunSpec",
    "SDKError",
    "SerializationError",
    "Server",
    "Tool",
    "ToolCall",
    "ToolCatalogError",
    "ToolNotFoundError",
    "ToolResolutionError",
    "Transport",
    "TransportError",
    "UnsupportedVersionError",
    "VersionError",
    "VersionMismatchError",
    "VersionNegotiation",
    "Workspace",
    "WorkspaceActiveError",
    "WorkspaceError",
    "WorkspaceManager",
    "WorkspaceNotFoundError",
]
