"""Lint ratchet — enforce the full ruff rule set on files not in the
baseline, and no-more-than-baseline counts on files that are.

Why a ratchet (see CONTRIBUTING.md "Lint & format"): this codebase was
written by 4 parallel build terminals before any linter existed. The
baseline file (scripts/lint-baseline.txt) records how many violations
each debt-carrying file had when the linter was introduced. The rule:

- a file NOT in the baseline must have ZERO ruff violations;
- a file IN the baseline must not gain any (count <= its baseline count).

Both directions are enforced, so the debt can only shrink: clean a
file below its count and `--update-baseline` graduates it from the list.

Usage (run from the repo root):
    python scripts/lint_ratchet.py                # enforce (exit 1 on new debt)
    python scripts/lint_ratchet.py --update-baseline   # refresh counts

Assumes ruff is importable as a subprocess (`ruff check --output-format
concise`); exits with a clear message if it isn't.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE_FILE = REPO_ROOT / "scripts" / "lint-baseline.txt"


def load_baseline() -> dict[str, int]:
    """Parse lint-baseline.txt into {posix relpath: allowed count}.

    Blank lines and lines starting with '#' are ignored, except that a
    line of the form '#<path>:<count>' (the emitted commented format)
    IS parsed — the file is human-readable documentation AND data.
    """
    out: dict[str, int] = {}
    if not BASELINE_FILE.is_file():
        return out
    for raw in BASELINE_FILE.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            line = line[1:]
        if ":" not in line:
            continue
        path, _, count = line.rpartition(":")
        path = path.strip()
        if not path or not count.strip().isdigit():
            continue
        out[path.replace("\\", "/")] = int(count)
    return out


def current_counts() -> dict[str, int]:
    """Run ruff check, returning {posix relpath: violation count}."""
    if shutil.which("ruff") is None:
        print(
            "error: ruff is not installed — run scripts/dev-setup.sh "
            '(or `pip install -e ".[dev]"`)',
            file=sys.stderr,
        )
        raise SystemExit(3)
    proc = subprocess.run(
        ["ruff", "check", "--no-cache", "--output-format", "concise", "."],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    counts: dict[str, int] = {}
    for line in proc.stdout.splitlines():
        if ":" not in line:
            continue
        path = line.split(":", 1)[0].strip()
        if not path:
            continue
        key = path.replace("\\", "/")
        counts[key] = counts.get(key, 0) + 1
    return counts


def main(argv: list[str] | None = None) -> int:
    """Enforce (or with --update-baseline, rewrite) the lint ratchet."""
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--update-baseline",
        action="store_true",
        help="rewrite scripts/lint-baseline.txt from current counts",
    )
    args = ap.parse_args(argv)

    baseline = load_baseline()
    counts = current_counts()

    if args.update_baseline:
        lines = [f"#{p}:{n}" for p, n in sorted(counts.items())]
        header = (
            'Lint baseline (ratchet) - see CONTRIBUTING.md "Lint & format".\n'
            "Format: '#<path>:<count>' - the file may carry at most <count>\n"
            "ruff violations. Not listed = zero violations required.\n"
            "Regenerated by `python scripts/lint_ratchet.py --update-baseline`.\n"
        )
        BASELINE_FILE.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
        print(f"baseline updated: {len(lines)} file(s) carry lint debt")
        return 0

    new_debt: list[str] = []  # not in baseline, has violations
    worse: list[str] = []  # in baseline, count grew
    for path, n in sorted(counts.items()):
        allowed = baseline.get(path, 0)
        if n > allowed:
            entry = f"  {path}: {n} violation(s) (allowed: {allowed})"
            (worse if path in baseline else new_debt).append(entry)
    for entry in sorted(new_debt + worse):
        print(entry)

    if new_debt or worse:
        print(
            "\nnew lint debt is not allowed — the ratchet only lets counts go down.",
            file=sys.stderr,
        )
        print(
            "fix the files above or run "
            "`python scripts/lint_ratchet.py --update-baseline` after "
            "deliberately accepting the debt.",
            file=sys.stderr,
        )
        return 1

    in_baseline_clean = [p for p in baseline if p not in counts]
    if in_baseline_clean:
        print(
            f"note: {len(in_baseline_clean)} baseline file(s) are now "
            "fully clean — graduate them: "
            "`python scripts/lint_ratchet.py --update-baseline`"
        )
    print(
        f"lint ratchet OK ({len(counts)} file(s) with violations, all within baseline)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
